### ISSUE TITLE
Edges or transitions?

### ISSUE THREAD

**Issue by strejcek** [adl/hoaf#57]
In the format description, we always use the term "transition" except the part describing the automaton body, where the term "edge" is used consistently (probably because it is also used in the formal grammar defining the syntax). Do we want to unify the terminology or is it ok?

**Comment by adl** [comment]
I like the convention that an *edge* labeled by a formula is a way to group several *transitions* labeled by letters, or AP assignments.  However I'm not sure having this convention is very practical here (partly because of #38), and this somehow goes against the name of `trans-acc` and `trans-labels`.

If we do not care about the edge/transition difference, I guess it's easier to use *transition* everywhere, isn't it?

**Comment by strejcek** [comment]
Do I understand it right that you suggest to replace "edge" with "trans" in the grammar and talk just about transitions? It's fine for me.

**Comment by adl** [comment]
> Do I understand it right that you suggest to replace "edge" with "trans" in the grammar and talk just about transitions?

Yes.  I can't say I'm overly fond of this, but at least I don't have a
better suggestion.

**Comment by strejcek** [comment]
Solved by pull request #60 (already merged to v1.1).
