### ISSUE TITLE
Figures referenced from examples in README.md are not working

### ISSUE THREAD

**Issue by ondrik** [adl/hoaf#67]
e.g. https://github.com/adl/hoaf/blob/master/figures/aut1.svg

**Comment by adl** [comment]
That's because those figures are generated by the Makefile when we build the web site, and the `README.md` you are looking at is just a source file for that web site as well.

See http://adl.github.io/hoaf/ for the result including the figures, and in particular http://adl.github.io/hoaf/examples.html if you just want the figures.

**Comment by ondrik** [comment]
Hi,

On 05/04/2017 01:42 PM, Alexandre Duret-Lutz wrote:
> That's because those figures are generated by the Makefile when we build the web site, and the `README.md` you are looking at is just a source file for that web site as well.
> 
> See http://adl.github.io/hoaf/ for the result including the figures, and in particular http://adl.github.io/hoaf/examples.html if you just want the figures.

got it, sorry for the false positive :-)

  Best,
              Ondra
-- 
Ondrej Lengal  <ondra.lengal@gmail.com> （龍安卓）
----------------------------------------------------------------
GPG:     40FD 3AE9 0BFA B151 4358  6194 5792 8315 149F 91C8
